version: '3.8'

services:
  app:
    image: rccmanagementsystem:latest
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_URL
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - REDIS_URL
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  db-test:
    image: postgres:latest
    ports:
      - "55432:5432"
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  session-store:
    image: redis:latest
    ports:
      - "6379:6379"
volumes:
  postgres_volume:
