micronaut:
  application:
    name: rccmanagementsystem
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    intercept-url-map:
      - access: isAnonymous()
        pattern: /swagger/**
      - access: isAnonymous()
        pattern: /swagger-ui/**
    authentication: session
    endpoints:
      login:
        enabled: true
        path: "/api/login"
      logout:
        enabled: true
        path: "/api/logout"
        get-allowed: false
    redirect:
      enabled: false
  session:
    http:
      cookie-same-site: lax
      header: false
      redis:
        enabled: true
  server:
    netty:
      access-logger:
        enabled: true
    cors:
      enabled: true
      single-header: true
      configurations:
        web:
          allowedOrigins:
            - "${ALLOWED_ORIGIN}"
netty:
  default:
    allocator:
      max-order: 3
flyway:
  datasources:
    default:
      enabled: false
redis:
  uri: "${REDIS_URL}"
datasources:
  default:
    username: "${POSTGRES_USER}"
    url: "${POSTGRES_URL}"
    password: "${POSTGRES_PASSWORD}"
